#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "blocky"
name = "Blocky"
description.en = "Fast and lightweight DNS proxy as ad-blocker for local network"
description.fr = "Proxy DNS rapide et léger comme bloqueur de publicités pour le réseau local"

version = "0.28.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://0xerr0r.github.io/blocky/latest/"
admindoc = "https://0xerr0r.github.io/blocky/latest/"
code = "https://github.com/0xERR0R/blocky"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/0xERR0R/blocky/releases/download/v0.28.2/blocky_v0.28.2_Linux_x86_64.tar.gz"
    amd64.sha256 = "bc93921fb033c25370808639f1f6b62f2356d14cfa00a8e110b514f5001caed0"
    arm64.url = "https://github.com/0xERR0R/blocky/releases/download/v0.28.2/blocky_v0.28.2_Linux_arm64.tar.gz"
    arm64.sha256 = "e7adb5bdff391c8fe88376ed861ee5dd1ae107ea3cb375cb8cc17371846b26b1"
    armhf.url = "https://github.com/0xERR0R/blocky/releases/download/v0.28.2/blocky_v0.28.2_Linux_armv7.tar.gz"
    armhf.sha256 = "ed7e879aad35eb8382b3dfdf8c34abd3566406ec46a5cc4c5ef82d3f37319afc"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
